In [129]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import nltk
nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to C:\Users\Nishanth
[nltk_data]     S\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Nishanth
[nltk_data]     S\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [130]:
data=pd.read_csv("C:\\Users\\Nishanth S\\Desktop\\class\\NLP_project\\smsspamcollection.tsv",sep='\t')
data

,label,message,length,punct
0,ham,"Go until jurong point, crazy.. Available only ...",111,9
1,ham,Ok lar... Joking wif u oni...,29,6
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,155,6
3,ham,U dun say so early hor... U c already then say...,49,6
4,ham,"Nah I don't think he goes to usf, he lives aro...",61,2
...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,160,8
5568,ham,Will ü b going to esplanade fr home?,36,1
5569,ham,"Pity, * was in mood for that. So...any other s...",57,7
5570,ham,The guy did some bitching but I acted like i'd...,125,1


In [131]:
le=LabelEncoder()
data["label"]=le.fit_transform(data["label"])
data

,label,message,length,punct
0,0,"Go until jurong point, crazy.. Available only ...",111,9
1,0,Ok lar... Joking wif u oni...,29,6
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,6
3,0,U dun say so early hor... U c already then say...,49,6
4,0,"Nah I don't think he goes to usf, he lives aro...",61,2
...,...,...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...,160,8
5568,0,Will ü b going to esplanade fr home?,36,1
5569,0,"Pity, * was in mood for that. So...any other s...",57,7
5570,0,The guy did some bitching but I acted like i'd...,125,1


In [132]:
y=data['label']
x=data["message"]

In [133]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=0)



In [134]:
feature=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)
x_train=feature.fit_transform(x_train)
x_test=feature.transform(x_test)

In [135]:
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [136]:
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [137]:
accuracy_score(y_train,lr.predict(x_train))

0.9639203015616586

In [138]:
accuracy_score(y_test,lr.predict(x_test))

0.9617868675995694

In [139]:
new_mail=['U dun say so early hor... U c already then say...	49	6']
new_mail_feature=feature.transform(new_mail)
email_det=lr.predict(new_mail_feature)
if email_det[0]==1:
    print("EMAIL IS SPAM")
else:
    print("EMAIL IS NOT SPAM")

EMAIL IS HAM


In [140]:
filename='spam_detection.sav'
pickle.dump(lr,open(filename,'wb'))

In [141]:
model=pickle.load(open("C:\\Users\\Nishanth S\\Desktop\\class\\NLP_project\\spam_detection.sav",'rb'))
model

LogisticRegression()

In [142]:
mail_pred=model.predict(new_mail_feature)
mail_pred

array([0])

In [143]:
spam_mail=["You are awarded a SiPix Digital Camera! call 09061221061 from landline. Delivery within 28days. T Cs Box177. M221BP. 2yr warranty. 150ppm. 16 . p p£3.99	152	9"]
spam_mail_feature=feature.transform(spam_mail)
spam_pred=model.predict(spam_mail_feature)
spam_pred

array([1])

In [145]:
spam_mail1=["Urgent UR awarded a complimentary trip to EuroDisinc Trav, Aco&Entry41 Or £1000. To claim txt DIS to 87121 18+6*£1.50(moreFrmMob. ShrAcomOrSglSuplt)10, LS1 3AJ	159	10"]
spam_mail1_feature=feature.transform(spam_mail1)
spam_pred1=model.predict(spam_mail1_feature)
spam_pred1

array([1])

In [146]:
spam_mail2=["Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed £1000 cash or £5000 prize!	137	2"]
spam_mail2_feature=feature.transform(spam_mail2)
spam_pred2=model.predict(spam_mail2_feature)
spam_pred2

array([1])